title: GIVE Engineering
logo: /assets/img/logo.png
description: Onward and upward
show_downloads: false
google_analytics: UA-31488943-6
theme: jekyll-theme-minimal
future: true

github:
  is_project_page: false

excerpt_separator: "<!---excerpt--->"

paginate: 50

plugins:
  - jekyll-paginate
